/**
 * Gojek Authentication Example
 * 
 * Demonstrates the full login flow using captured iOS traffic.
 * 
 * FLOWS:
 * 1. OTP flow  - works if you can provide the OTP code
 * 2. PIN flow  - requires validation_jwt (RS256 JWT generated by iOS app, cannot be replicated)
 * 3. SSO flow  - works on trusted/already-logged-in devices
 * 
 * LIMITATION: All endpoints require X-E1 signature header generated by the iOS/Android app.
 * Without X-E1, the API returns "GoPay-1000". You must capture X-E1 from a real device
 * using mitmproxy and pass it via signatureHeaders. X-E1 is per-request and expires quickly.
 * 
 * Usage:
 *   PHONE_NUMBER=<PHONE_NUMBER> node auth.js
 */

require('dotenv').config({ path: require('path').resolve(__dirname, '../../../.env') });
const { AuthApi, createIOSDeviceConfig } = require('../../../sdk/auth-gojek-node/dist/index.js');

const PHONE_NUMBER = process.env.GOJEK_PHONE_NUMBER;
const COUNTRY_CODE = process.env.GOJEK_COUNTRY_CODE || '+62';
const CLIENT_ID = process.env.GOJEK_CLIENT_ID || 'gojek:consumer:app';
const CLIENT_SECRET = process.env.GOJEK_CLIENT_SECRET || '';

if (!PHONE_NUMBER) {
  console.error('Error: GOJEK_PHONE_NUMBER is required. Set it in .env file.');
  process.exit(1);
}
if (!CLIENT_SECRET) {
  console.error('Error: GOJEK_CLIENT_SECRET is required. Obtain it by decompiling the Gojek APK.');
  process.exit(1);
}

// X-E1 captured from mitmproxy — replace with fresh values from your device
// These expire quickly and are per-request, so you need to capture them fresh
const CAPTURED_X_E1 = process.env.GOJEK_X_E1 || '';

async function loginWithOTP() {
  const device = createIOSDeviceConfig();
  const auth = new AuthApi(device, CLIENT_ID, CLIENT_SECRET);

  console.log('=== Gojek OTP Login Flow ===\n');
  console.log(`Phone: ${COUNTRY_CODE}${PHONE_NUMBER}`);
  console.log(`Device UniqueId: ${device.uniqueId}\n`);

  // Step 1: Get login methods
  console.log('Step 1: Getting login methods...');
  const methodsResp = await auth.getLoginMethods(PHONE_NUMBER, COUNTRY_CODE, {
    X_E1: CAPTURED_X_E1,
  });

  if (!methodsResp.success || !methodsResp.data) {
    console.error('Failed:', methodsResp.errors);
    return;
  }

  const { verification_id, methods, default_method } = methodsResp.data;
  console.log(`  verification_id: ${verification_id}`);
  console.log(`  available methods: ${methods.join(', ')}`);
  console.log(`  default method: ${default_method}\n`);

  // Step 2: Initiate OTP (choose otp_sms or otp_wa)
  const otpMethod = methods.includes('otp_sms') ? 'otp_sms' : 'otp_wa';
  console.log(`Step 2: Initiating ${otpMethod}...`);
  const initiateResp = await auth.initiateVerification(
    verification_id,
    otpMethod,
    PHONE_NUMBER,
    COUNTRY_CODE,
    'login_1fa',
    { X_E1: CAPTURED_X_E1 }
  );

  if (!initiateResp.success || !initiateResp.data) {
    console.error('Failed:', initiateResp.errors);
    return;
  }

  const { otp_token, otp_length } = initiateResp.data;
  console.log(`  otp_token: ${otp_token}`);
  console.log(`  otp_length: ${otp_length}\n`);

  // Step 3: Verify OTP (prompt user for code)
  const otp = process.env.OTP_CODE;
  if (!otp) {
    console.log(`OTP sent! Set OTP_CODE env var and re-run to complete login.`);
    console.log(`  e.g. OTP_CODE=1234 GOJEK_PHONE_NUMBER=${PHONE_NUMBER} node auth.js`);
    return;
  }

  console.log(`Step 3: Verifying OTP ${otp}...`);
  const verifyResp = await auth.verifyCode(
    verification_id,
    otpMethod,
    { otp: otp, otp_token: otp_token },
    'login_1fa',
    { X_E1: CAPTURED_X_E1 }
  );

  if (!verifyResp.success || !verifyResp.data) {
    console.error('Failed:', verifyResp.errors);
    return;
  }

  const { verification_token } = verifyResp.data;
  console.log(`  verification_token: ${verification_token.substring(0, 40)}...\n`);

  // Step 4: Get account list
  console.log('Step 4: Getting account list...');
  const accountListResp = await auth.getAccountList(verification_token, { X_E1: CAPTURED_X_E1 });

  if (!accountListResp.success || !accountListResp.data) {
    console.error('Failed:', accountListResp.errors);
    return;
  }

  const { account_list, '1fa_token': token1fa } = accountListResp.data;
  const account = account_list[0];
  console.log(`  account_id: ${account.account_id}\n`);

  // Step 5: Exchange for access token
  console.log('Step 5: Exchanging for access token...');
  const tokenResp = await auth.exchangeToken(token1fa, account.account_id, 'cvs', {
    X_E1: CAPTURED_X_E1,
  });

  if (!tokenResp.success || !tokenResp.data) {
    console.error('Failed:', tokenResp.errors);
    return;
  }

  console.log(`\n✓ Login successful!`);
  console.log(`  access_token: ${tokenResp.data.access_token.substring(0, 60)}...`);
}

async function loginWithSSO() {
  const device = createIOSDeviceConfig();
  const auth = new AuthApi(device, CLIENT_ID, CLIENT_SECRET);

  console.log('=== Gojek SSO Login Flow (trusted device) ===\n');

  // SSO login — only works on devices previously logged in
  console.log('Step 1: SSO login...');
  const ssoResp = await auth.ssoLogin({ X_E1: CAPTURED_X_E1 });

  if (!ssoResp.success || !ssoResp.data) {
    console.error('Failed:', ssoResp.errors);
    return;
  }

  const { account_list, auth_code } = ssoResp.data;
  const account = account_list[0];
  console.log(`  account_id: ${account.account_id}`);
  console.log(`  auth_code: ${auth_code.substring(0, 40)}...\n`);

  // Exchange auth_code for access token
  console.log('Step 2: Exchanging auth_code for access token...');
  const tokenResp = await auth.exchangeToken(auth_code, account.account_id, 'auth_code', {
    X_E1: CAPTURED_X_E1,
  });

  if (!tokenResp.success || !tokenResp.data) {
    console.error('Failed:', tokenResp.errors);
    return;
  }

  console.log(`\n✓ SSO Login successful!`);
  console.log(`  access_token: ${tokenResp.data.access_token.substring(0, 60)}...`);
}

// Run OTP flow by default, SSO if --sso flag passed
const flow = process.argv.includes('--sso') ? loginWithSSO : loginWithOTP;
flow().catch(err => {
  if (err.response) {
    console.error('API Error:', err.response.status, JSON.stringify(err.response.data, null, 2));
  } else {
    console.error('Error:', err.message);
  }
});